# options.sh - generated by tools/kb.py gen from kb/*.toml. Do not edit:
# change the knowledge base and run tools/kb.py gen.

OYG_KB_GENS='5.6 6.5 8.3 9.2 10.3 11.2'
OYG_KB_RUN='10.3'
OYG_OPTIONS='acr ads adid promos lgchannels diagnostics usage-logs consents hbbtv-tracking hbbtv voice mic voice-core capture airplay cast phone miracast uei-cloud lan thinq google-home buddy-sports ai backup-presence universal-control trackers store-traffic remote-config remote-support account terms'
OYG_CATEGORIES='ads usage voice screen casting cloud network access'
CAT_ads_title='Ads and content recognition'; CAT_ads_blurb='Ads and what watches the screen.'
CAT_usage_title='Usage data and diagnostics'; CAT_usage_blurb='Logs, crash reports and consents.'
CAT_voice_title='Voice and microphones'; CAT_voice_blurb='Assistants and microphones.'
CAT_screen_title='Screen'; CAT_screen_blurb='Screen captures.'
CAT_casting_title='Casting and phones'; CAT_casting_blurb='How other devices reach the TV.'
CAT_cloud_title='LG cloud and smart home'; CAT_cloud_blurb='LG'\''s cloud, smart home and AI.'
CAT_network_title='Network'; CAT_network_blurb='Hostnames sent nowhere.'
CAT_access_title='Remote access and prompts'; CAT_access_blurb='Remote access, accounts and prompts.'

PRESET_recommended='acr ads adid promos diagnostics usage-logs consents hbbtv-tracking voice mic capture thinq google-home buddy-sports backup-presence trackers remote-support terms'
PRESET_recommended_name='Recommended'; PRESET_recommended_summary='Blocks tracking and ads; keeps casting, phone apps and the Store working.'; PRESET_recommended_warning=''
PRESET_strict='acr ads adid promos lgchannels diagnostics usage-logs consents hbbtv-tracking voice mic capture airplay cast phone miracast uei-cloud lan thinq google-home buddy-sports ai backup-presence trackers remote-support account terms'
PRESET_strict_name='Strict'; PRESET_strict_summary='Also turns off casting, phone control and LG Channels, closes the TV to your network and blocks your LG account.'; PRESET_strict_warning=''
PRESET_lockdown='acr ads adid promos lgchannels diagnostics usage-logs consents hbbtv-tracking voice mic voice-core capture airplay cast phone miracast uei-cloud lan thinq google-home buddy-sports ai backup-presence universal-control trackers store-traffic remote-config remote-support account terms'
PRESET_lockdown_name='Lockdown'; PRESET_lockdown_summary='Also disables some LG system services. Makes settings slow to open, breaks automatic time / timezone and more.'; PRESET_lockdown_warning='Lockdown is not recommended and may cause unexpected behaviour.'
OYG_PRESETS='recommended strict lockdown'

# --- acr
OPT_acr_category='ads'
OPT_acr_name='Content recognition (ACR)'
OPT_acr_what='Stops content recognition (ACR) of what you watch.'
OPT_acr_breaks='Live Plus overlays'
OPT_acr_hook=''
OPT_acr_warning=''
OPT_acr_presets='recommended strict lockdown'; OPT_acr_untested=0
OPT_acr_spec='
acr||?|acr2||com.webos.service.acr|L=dynamic
adoverlay||?|adoverlay-service||com.webos.service.adoverlay|L=dynamic
adoverlay-legacy|adoverlay.service|?|adoverlay|||
livepick-plus||?|livepick-plus||com.webos.service.livepickplus|L=dynamic
'
OPT_acr_spec_t=''
OPT_acr_released='
objectdetection||?|objectdetection|
objectdetectionutilizer||?|objectdetectionutilizer|
'
OPT_acr_sdx=''
OPT_acr_hosts='alphonso.tv cdn-aas-campaigns.alphonso.tv konograma.com marker.konograma.com marker2.konograma.com prov-lg.alphonso.tv eulacheck.alphonso.tv config-overlay-ads.alphonso.tv {ric}.videoacr.lgtvcommon.com moments-edge-service.edgevideo.ai moments-edge-service-342233178764.us-central1.run.app'
OPT_acr_hosts_t=''
OPT_acr_settings='
option|livePlus|"off"
option|livePromotion|"off"
'
OPT_acr_settings_t=''
OPT_acr_apps='com.webos.app.acrcomponent com.webos.app.acrhdmi1 com.webos.app.acrhdmi2 com.webos.app.acrhdmi3 com.webos.app.acrhdmi4 com.webos.app.acroverlay com.webos.app.adoverlay com.webos.app.adoverlayex com.webos.app.adhdmi1 com.webos.app.adhdmi2 com.webos.app.adhdmi3 com.webos.app.adhdmi4 com.webos.app.overlaycontainer com.webos.app.overlaycontainerex com.webos.app.overlaycontainerhdmi1 com.webos.app.overlaycontainerhdmi2 com.webos.app.overlaycontainerhdmi3 com.webos.app.overlaycontainerhdmi4'
OPT_acr_apps_t=''

# --- ads
OPT_ads_category='ads'
OPT_ads_name='Ad services'
OPT_ads_what='Stops LG'\''s ad ID, ad logs and ad apps, and turns the ad settings off.'
OPT_ads_breaks='Reset advertising ID, LG Shop'
OPT_ads_hook=''
OPT_ads_warning=''
OPT_ads_presets='recommended strict lockdown'; OPT_ads_untested=0
OPT_ads_spec='
admanager||?|admanager||com.webos.service.admanager|L=dynamic
lsa||/usr/sbin/com.webos.service.lsa|||com.webos.service.lsa|L=dynamic
'
OPT_ads_spec_t=''
OPT_ads_released=''
OPT_ads_sdx='lgshop_secure lgshoplog_secure'
OPT_ads_hosts='ads.lgtvcommon.com aic.ads.lgtvcommon.com ad.lgappstv.com lgsmartad.com info.lgsmartad.com de.info.lgsmartad.com smart.adtvc.app adsdtvc.com initscr.lge.com {ric}.api.adts.lgtvcommon.com {ric}.videoads.lgtvcommon.com {ric}.fooddelivery.lgtvcommon.com {ric}.lgshopsvc.lgappstv.com'
OPT_ads_hosts_t=''
OPT_ads_settings='
general|screenSaverAd|"off"
general|adCookie|"off"
general|customizedAd|"off"
general|lmt|"on"
general|doNotSellMyPersonalInformation|"on"
option|thirdPartyCookie|"off"
'
OPT_ads_settings_t=''
OPT_ads_apps='com.webos.app.fooddelivery com.webos.app.fooddeliveryex com.webos.app.fooddeliveryhdmi1 com.webos.app.fooddeliveryhdmi2 com.webos.app.fooddeliveryhdmi3 com.webos.app.fooddeliveryhdmi4 com.webos.app.videoads com.webos.app.cmp-client com.webos.app.adapp'
OPT_ads_apps_t=''

# --- adid
OPT_adid_category='ads'
OPT_adid_name='Opt-out advertising ID'
OPT_adid_what='Set LG'\''s advertising ID to zeros (opt-out).'
OPT_adid_breaks=''
OPT_adid_hook='adid'
OPT_adid_warning=''
OPT_adid_presets='recommended strict lockdown'; OPT_adid_untested=0
OPT_adid_spec=''
OPT_adid_spec_t=''
OPT_adid_released=''
OPT_adid_sdx=''
OPT_adid_hosts=''
OPT_adid_hosts_t=''
OPT_adid_settings=''
OPT_adid_settings_t=''
OPT_adid_apps=''
OPT_adid_apps_t=''

# --- promos
OPT_promos_category='ads'
OPT_promos_name='Home promotions and recommendations'
OPT_promos_what='Stops the promoted rows and AI tips on Home.'
OPT_promos_breaks='Home preview rows, promo cards, AI tips'
OPT_promos_hook=''
OPT_promos_warning=''
OPT_promos_presets='recommended strict lockdown'; OPT_promos_untested=0
OPT_promos_spec='
contentminer|contentminer.service|?|contentminer||com.webos.service.contentminer|L=static
nudge|nudge.service|?|nudge||com.webos.service.nudge|L=static
sdp-server-notice||?|sdp-server-notice||com.webos.service.sdpservernotice|L=dynamic
'
OPT_promos_spec_t=''
OPT_promos_released=''
OPT_promos_sdx='nudge_secure homeprv_secure recommend_secure tlamp_secure web_browser_rcmd qcard sdp_onnow cpv_secure upp sdp_aiplatform_proactiveai wise30_device sdp_aiplatform_aiconcierge lg_gallery_plus'
OPT_promos_hosts='homeprv.lgtvcommon.com recommend.lgtvcommon.com nudge.lgtvcommon.com eic.nudge.lgtvcommon.com eic.wiseconfig.lgtvcommon.com pnv.lgtvcommon.com qcardservice.lgtvcommon.com lggalleryplus.com cf-kic.lggalleryplus.com {ric}.lggalleryplus.com {ric}.lgrecommends.lgappstv.com'
OPT_promos_hosts_t=''
OPT_promos_settings='
general|homePromotion|"off"
general|personalRecommend|{"value":"off","changedByUser":true}
general|aiNudge|"off"
general|aiSettingsNudge|"off"
general|lifeAlarm|"off"
general|welcomeFeature|"off"
option|webOSPromotionVideo|"off"
other|contentRecommendation|"off"
general|aiChannel|"off"
'
OPT_promos_settings_t=''
OPT_promos_apps='com.webos.app.newandhot'
OPT_promos_apps_t=''

# --- lgchannels
OPT_lgchannels_category='ads'
OPT_lgchannels_name='LG Channels'
OPT_lgchannels_what='Turns off LG'\''s free ad-supported channels.'
OPT_lgchannels_breaks='LG Channels'
OPT_lgchannels_hook=''
OPT_lgchannels_warning=''
OPT_lgchannels_presets='strict lockdown'; OPT_lgchannels_untested=0
OPT_lgchannels_spec='
lgchannelurl||/usr/sbin/lgchannelurl|lgchannelurl||com.webos.service.lgchannelurl|L=dynamic
'
OPT_lgchannels_spec_t=''
OPT_lgchannels_released=''
OPT_lgchannels_sdx='cdp_service_secure'
OPT_lgchannels_hosts='{ric}.cdpsvc.lgtvcommon.com {ric}.cdplauncher.lgtvcommon.com {ric}.lgchhomeapp.lgtvcommon.com'
OPT_lgchannels_hosts_t=''
OPT_lgchannels_settings='
option|channelplus|"off"
option|lgChannelAutoStart|"off"
general|lgChannelAutoLaunch|"off"
'
OPT_lgchannels_settings_t=''
OPT_lgchannels_apps=''
OPT_lgchannels_apps_t=''

# --- diagnostics
OPT_diagnostics_category='usage'
OPT_diagnostics_name='Crash and log uploads'
OPT_diagnostics_what='Stops crash reports and log uploads to LG.'
OPT_diagnostics_breaks=''
OPT_diagnostics_hook='diagnostics'
OPT_diagnostics_warning=''
OPT_diagnostics_presets='recommended strict lockdown'; OPT_diagnostics_untested=0
OPT_diagnostics_spec='
uploadd|uploadd.service|?|uploadd||com.palm.uploadd|L=dynamic
rdxd|rdxd.service|?|rdxd||com.webos.rdxd|L=static
rdx_reporter||?|rdx_reporter|||
remotelogger|remotelogger.service|?|remotelogger|||
'
OPT_diagnostics_spec_t=''
OPT_diagnostics_released=''
OPT_diagnostics_sdx='sdp_logging rdx_secure rdxdev_secure'
OPT_diagnostics_hosts='rdl.lgtvcommon.com {cc}.rdl.lgtvcommon.com qt2-kic.service.lgtvcommon.com'
OPT_diagnostics_hosts_t=''
OPT_diagnostics_settings='
option|dbgLogUpload|false
option|faultLogUpload|false
'
OPT_diagnostics_settings_t=''
OPT_diagnostics_apps=''
OPT_diagnostics_apps_t=''

# --- usage-logs
OPT_usage_logs_category='usage'
OPT_usage_logs_name='Viewing and usage logs'
OPT_usage_logs_what='Stops the logs of what you watch and use.'
OPT_usage_logs_breaks='Reset usage data, recent-apps order, monthly report'
OPT_usage_logs_hook=''
OPT_usage_logs_warning=''
OPT_usage_logs_presets='recommended strict lockdown'; OPT_usage_logs_untested=0
OPT_usage_logs_spec='
service-logger|service-logger.service|?|service-logger||com.webos.service.logger|L=static
user-context-manager|user-context-manager.service|?|user-context-manager||com.webos.service.usercontextmanager|L=static
ocpservice|ocp.service|?|ocpservice||com.webos.service.ocp|L=static
ftms|ftms.service|?|ftms||com.webos.service.ftms|L=static
scd-service||/usr/sbin/scd-service|scd-service||com.webos.service.scd|L=dynamic
user-intent-manager||/usr/sbin/user-intent-manager|user-intent-manager||com.webos.service.userintentmanager|L=dynamic
'
OPT_usage_logs_spec_t=''
OPT_usage_logs_released=''
OPT_usage_logs_sdx='ibis_stat_secure nudge_log_secure cdpbeacon_secure'
OPT_usage_logs_hosts='cdpbeacon.lgtvcommon.com {ric}.cdpbeacon.lgtvcommon.com {ric}.cdpbeacon2.lgtvcommon.com {ric}.ocp.lgtviot.com {ric}.homegym.lgappstv.com'
OPT_usage_logs_hosts_t='{cc}.elastic.lgwebostv.com aj7.elastic.lgwebostv.com'
OPT_usage_logs_settings='
option|usageCare|false
option|watchedListCollection|"off"
'
OPT_usage_logs_settings_t=''
OPT_usage_logs_apps=''
OPT_usage_logs_apps_t=''

# --- consents
OPT_consents_category='usage'
OPT_consents_name='Tracking consents'
OPT_consents_what='Declines every tracking and ad consent.'
OPT_consents_breaks=''
OPT_consents_hook='consents'
OPT_consents_warning=''
OPT_consents_presets='recommended strict lockdown'; OPT_consents_untested=0
OPT_consents_spec=''
OPT_consents_spec_t=''
OPT_consents_released=''
OPT_consents_sdx=''
OPT_consents_hosts=''
OPT_consents_hosts_t=''
OPT_consents_settings=''
OPT_consents_settings_t=''
OPT_consents_apps=''
OPT_consents_apps_t=''

# --- hbbtv-tracking
OPT_hbbtv_tracking_category='usage'
OPT_hbbtv_tracking_name='HbbTV tracking'
OPT_hbbtv_tracking_what='Asks broadcasters'\'' interactive pages not to track you.'
OPT_hbbtv_tracking_breaks=''
OPT_hbbtv_tracking_hook=''
OPT_hbbtv_tracking_warning=''
OPT_hbbtv_tracking_presets='recommended strict lockdown'; OPT_hbbtv_tracking_untested=0
OPT_hbbtv_tracking_spec=''
OPT_hbbtv_tracking_spec_t=''
OPT_hbbtv_tracking_released=''
OPT_hbbtv_tracking_sdx=''
OPT_hbbtv_tracking_hosts=''
OPT_hbbtv_tracking_hosts_t=''
OPT_hbbtv_tracking_settings='
option|hbbTvDnt|"on"
option|hbbTvDeviceId|"offByUser"
'
OPT_hbbtv_tracking_settings_t=''
OPT_hbbtv_tracking_apps=''
OPT_hbbtv_tracking_apps_t=''

# --- hbbtv
OPT_hbbtv_category='usage'
OPT_hbbtv_name='HbbTV'
OPT_hbbtv_what='Turns off broadcasters'\'' interactive pages.'
OPT_hbbtv_breaks='Freeview Plus, red button'
OPT_hbbtv_hook=''
OPT_hbbtv_warning=''
OPT_hbbtv_presets='strict lockdown'; OPT_hbbtv_untested=1
OPT_hbbtv_spec=''
OPT_hbbtv_spec_t=''
OPT_hbbtv_released=''
OPT_hbbtv_sdx=''
OPT_hbbtv_hosts=''
OPT_hbbtv_hosts_t=''
OPT_hbbtv_settings='
option|hbbTV|"off"
'
OPT_hbbtv_settings_t=''
OPT_hbbtv_apps=''
OPT_hbbtv_apps_t=''

# --- voice
OPT_voice_category='voice'
OPT_voice_name='Voice assistants and wake words'
OPT_voice_what='Stops the voice assistants and wake words.'
OPT_voice_breaks='Voice search, Alexa, ThinQ AI'
OPT_voice_hook='voice'
OPT_voice_warning=''
OPT_voice_presets='recommended strict lockdown'; OPT_voice_untested=0
OPT_voice_spec='
voiceinput_hidraw||?|voiceinput_hidraw||com.webos.service.voiceinput.hidraw|L=dynamic
voiceinput_sound||?|voiceinput_sound||com.webos.service.voiceinput.sound|L=dynamic
voiceinput_preprocessor||?|voiceinput_preprocessor||com.webos.service.voiceinput.preprocessor|L=dynamic
voiceinput_network||?|voiceinput_network||com.webos.service.voiceinput.network|L=dynamic
voiceclick||?|voiceclick||com.webos.service.voiceclick|L=dynamic
trigger_alexa||?|trigger_alexa||com.webos.service.trigger.alexa|L=dynamic
trigger_thinq||?|trigger_thinq||com.webos.service.trigger.thinq|L=dynamic
alexa-adapter||?|amazon-alexa-adapter||amazon.alexa.adapter.plugin|L=jailed,j=amazon.alexa.adapter
thinqai-adapter||?|lg.thinqai.adapter||lg.thinqai.adapter|L=jailed,j=lg.thinqai.adapter
thinqcn-adapter||/usr/sbin/lg-thinqcn-adapter|lg-thinqcn-adapter||lg.thinqcn.adapter|L=jailed,j=lg.thinqcn.adapter
nlpmanagercn||/usr/sbin/nlpmanagercn|nlpmanagercn||com.webos.service.nlpmanagercn|L=dynamic
sound-aware-adapter||/usr/sbin/sound-aware-adapter|sound-aware-adapter||com.webos.service.soundawareadapter|L=dynamic
voice-performer||/usr/sbin/performer|performer||com.webos.service.voice.performer.plugin|L=jailed,j=com.webos.service.voice.performer
'
OPT_voice_spec_t=''
OPT_voice_released='
airessrvallocator||?|airessrvallocator|
voiceconductor||?|voiceconductor|
'
OPT_voice_sdx='sdp_nais voice_proxy_secure'
OPT_voice_hosts='avsxappcaptiveportal.com wau.lgtvcommon.com he-kr-ai.lgthinq.com'
OPT_voice_hosts_t=''
OPT_voice_settings='
general|voiceLongDistance|"off"
'
OPT_voice_settings_t=''
OPT_voice_apps=''
OPT_voice_apps_t=''

# --- mic
OPT_mic_category='voice'
OPT_mic_name='Built-in microphone'
OPT_mic_what='Blocks the built-in microphone.'
OPT_mic_breaks='Hands-free voice'
OPT_mic_hook='mic'
OPT_mic_warning=''
OPT_mic_presets='recommended strict lockdown'; OPT_mic_untested=0
OPT_mic_spec=''
OPT_mic_spec_t=''
OPT_mic_released=''
OPT_mic_sdx=''
OPT_mic_hosts=''
OPT_mic_hosts_t=''
OPT_mic_settings=''
OPT_mic_settings_t=''
OPT_mic_apps=''
OPT_mic_apps_t=''

# --- voice-core
OPT_voice_core_category='voice'
OPT_voice_core_name='Voice framework and search'
OPT_voice_core_what='Also stops the voice framework and search.'
OPT_voice_core_breaks='Settings speed, automatic time, time zones, search'
OPT_voice_core_hook=''
OPT_voice_core_warning=''
OPT_voice_core_presets='lockdown'; OPT_voice_core_untested=0
OPT_voice_core_spec='
voiceconductor-block||/usr/sbin/voiceconductor|voiceconductor||com.webos.service.voiceconductor|L=static
voiceinput-hub||/usr/sbin/voiceinput|voiceinput||com.webos.service.voiceinput|L=static
nlpmanager||/usr/sbin/nlpmanager|nlpmanager||com.webos.service.nlpmanager|L=dynamic
'
OPT_voice_core_spec_t=''
OPT_voice_core_released=''
OPT_voice_core_sdx='sdp_search sdp_nlp'
OPT_voice_core_hosts=''
OPT_voice_core_hosts_t=''
OPT_voice_core_settings=''
OPT_voice_core_settings_t=''
OPT_voice_core_apps=''
OPT_voice_core_apps_t=''

# --- capture
OPT_capture_category='screen'
OPT_capture_name='Screen-capture shield'
OPT_capture_what='Hides the screen captures the OLED service keeps.'
OPT_capture_breaks=''
OPT_capture_hook='capture'
OPT_capture_warning=''
OPT_capture_presets='recommended strict lockdown'; OPT_capture_untested=0
OPT_capture_spec=''
OPT_capture_spec_t=''
OPT_capture_released=''
OPT_capture_sdx=''
OPT_capture_hosts=''
OPT_capture_hosts_t=''
OPT_capture_settings=''
OPT_capture_settings_t=''
OPT_capture_apps=''
OPT_capture_apps_t=''

# --- airplay
OPT_airplay_category='casting'
OPT_airplay_name='AirPlay'
OPT_airplay_what='Turns off AirPlay.'
OPT_airplay_breaks='AirPlay, HomeKit (Siri)'
OPT_airplay_hook=''
OPT_airplay_warning=''
OPT_airplay_presets='strict lockdown'; OPT_airplay_untested=0
OPT_airplay_spec='
airplay||/usr/sbin/airplay|airplay||airplay.service|L=dynamic
airplay-adaptor|airplay-adaptor.service|/usr/sbin/airplay-adaptor|airplay-adaptor||com.webos.service.airplayadaptor|L=static
mfi|mfi.service|/usr/sbin/mfi|mfi||com.webos.service.mfi|L=dynamic
'
OPT_airplay_spec_t=''
OPT_airplay_released=''
OPT_airplay_sdx='sdp_airplay'
OPT_airplay_hosts=''
OPT_airplay_hosts_t=''
OPT_airplay_settings=''
OPT_airplay_settings_t=''
OPT_airplay_apps=''
OPT_airplay_apps_t=''

# --- cast
OPT_cast_category='casting'
OPT_cast_name='Google Cast'
OPT_cast_what='Turns off Chromecast built-in.'
OPT_cast_breaks='Google Cast'
OPT_cast_hook=''
OPT_cast_warning=''
OPT_cast_presets='strict lockdown'; OPT_cast_untested=0
OPT_cast_spec='
chromecast-prov|chromecast-provisioning.service|?|chromecast-provisioning||com.webos.service.chromecast.provisioning|L=static
chromecast-cell||/media/system/apps/usr/palm/services/com.webos.chromecast.cell/com.webos.chromecast.cell|||com.webos.chromecast.cell|m,L=jailed,j=com.webos.chromecast
chromecast-core||/media/system/apps/usr/palm/services/com.webos.chromecast.core/com.webos.chromecast.core|||com.webos.chromecast.core|m,L=jailed,j=com.webos.chromecast
chromecast-log||/media/system/apps/usr/palm/services/com.webos.chromecast.log/com.webos.chromecast.log|||com.webos.chromecast.log|m,L=jailed,j=com.webos.chromecast
'
OPT_cast_spec_t=''
OPT_cast_released=''
OPT_cast_sdx=''
OPT_cast_hosts=''
OPT_cast_hosts_t=''
OPT_cast_settings=''
OPT_cast_settings_t=''
OPT_cast_apps=''
OPT_cast_apps_t=''

# --- phone
OPT_phone_category='casting'
OPT_phone_name='Phone apps and second screen'
OPT_phone_what='Stops phones controlling the TV over the network.'
OPT_phone_breaks='Phone remote apps, launching apps from a phone, LG Link'
OPT_phone_hook='phone'
OPT_phone_warning=''
OPT_phone_presets='strict lockdown'; OPT_phone_untested=0
OPT_phone_spec='
appcasting|appcasting.service|?|appcasting||com.webos.service.appcasting|L=static
dial-discovery||/usr/palm/services/com.webos.service.dial/discovery-server.js|||com.webos.service.dial|u,L=unified
lglink|||||com.webos.service.lglink|u,L=unified
'
OPT_phone_spec_t=''
OPT_phone_released=''
OPT_phone_sdx=''
OPT_phone_hosts=''
OPT_phone_hosts_t=''
OPT_phone_settings='
network|allowMobileDeviceAccess|false
'
OPT_phone_settings_t=''
OPT_phone_apps=''
OPT_phone_apps_t=''

# --- miracast
OPT_miracast_category='casting'
OPT_miracast_name='Screen Share'
OPT_miracast_what='Turns off Screen Share.'
OPT_miracast_breaks='Screen Share'
OPT_miracast_hook='miracast'
OPT_miracast_warning=''
OPT_miracast_presets='strict lockdown'; OPT_miracast_untested=0
OPT_miracast_spec='
avahi-daemon|avahi-daemon.service|?|avahi-daemon|||
avahi-adaptor|avahi-adaptor.service|?|avahi-adaptor||com.webos.service.dnssd|L=static
miracast|miracast.service|/usr/sbin/miracast|miracast||com.webos.service.miracast|L=static
'
OPT_miracast_spec_t=''
OPT_miracast_released=''
OPT_miracast_sdx=''
OPT_miracast_hosts=''
OPT_miracast_hosts_t=''
OPT_miracast_settings=''
OPT_miracast_settings_t=''
OPT_miracast_apps=''
OPT_miracast_apps_t=''

# --- uei-cloud
OPT_uei_cloud_category='casting'
OPT_uei_cloud_name='Universal Control cloud lookups'
OPT_uei_cloud_what='Stops Universal Control reporting your devices to UEI'\''s cloud.'
OPT_uei_cloud_breaks=''
OPT_uei_cloud_hook=''
OPT_uei_cloud_warning=''
OPT_uei_cloud_presets='strict lockdown'; OPT_uei_cloud_untested=0
OPT_uei_cloud_spec=''
OPT_uei_cloud_spec_t=''
OPT_uei_cloud_released=''
OPT_uei_cloud_sdx=''
OPT_uei_cloud_hosts='www.ueiwsp.com ueiwsp.com discovery.meethue.com'
OPT_uei_cloud_hosts_t=''
OPT_uei_cloud_settings=''
OPT_uei_cloud_settings_t=''
OPT_uei_cloud_apps=''
OPT_uei_cloud_apps_t=''

# --- lan
OPT_lan_category='casting'
OPT_lan_name='LAN firewall'
OPT_lan_what='Closes the TV to all inbound connections from your local network.'
OPT_lan_breaks='SSH, AirPlay, Google Cast, phone apps, Screen Share, network devices in Universal Control'
OPT_lan_hook='lan'
OPT_lan_warning=''
OPT_lan_presets='strict lockdown'; OPT_lan_untested=0
OPT_lan_spec=''
OPT_lan_spec_t=''
OPT_lan_released=''
OPT_lan_sdx=''
OPT_lan_hosts=''
OPT_lan_hosts_t=''
OPT_lan_settings=''
OPT_lan_settings_t=''
OPT_lan_apps=''
OPT_lan_apps_t=''

# --- thinq
OPT_thinq_category='cloud'
OPT_thinq_name='ThinQ and Home Hub'
OPT_thinq_what='Stops LG'\''s ThinQ cloud and smart-home links.'
OPT_thinq_breaks='ThinQ app, Home Hub, Matter, LG notifications'
OPT_thinq_hook=''
OPT_thinq_warning=''
OPT_thinq_presets='recommended strict lockdown'; OPT_thinq_untested=0
OPT_thinq_spec='
iot-client|iot-client.service|/usr/palm/services/com.webos.service.iotclient/iot-client|||com.webos.service.iotclient|L=dynamic
iot-client-bin||/usr/bin/iot-client||||
iot-proxy||?|iot-proxy||com.webos.service.iotproxy|L=dynamic
pushclient|com.webos.service.pushclient.service|/usr/sbin/com.webos.service.pushclient|||com.webos.service.pushclient|L=static
ruleengine|com.webos.service.ruleengine.service|/usr/sbin/com.webos.service.ruleengine|||com.webos.service.ruleengine|L=static
homeconnect||/usr/palm/services/com.webos.service.homeconnect/main.js|||com.webos.service.homeconnect|u,L=unified
iotframework||/usr/palm/services/com.webos.iotframework/com.webos.iotframework|com.webos.iotframework||com.webos.iotframework|L=dynamic
homey-bridge||/usr/sbin/webos-homey-bridge|webos-homey-bridge||com.webos.service.homeybridge|L=dynamic
homey-matter||/usr/sbin/homey-matter|homey-matter||com.webos.service.homeymatter|L=dynamic
matter||/usr/palm/services/com.webos.service.matter/chip-service|||com.webos.service.matter|L=dynamic
mycar|com.webos.service.mycar.service|/usr/sbin/com.webos.service.mycar|||com.webos.service.mycar|L=static
'
OPT_thinq_spec_t=''
OPT_thinq_released='
familycare|com.webos.service.familycare.service|/usr/palm/services/com.webos.service.familycare/index.js||familycare/index.js
alwaysready|alwaysready.service|?|alwaysready|
ai-inference|ai-inference-manager.service|?|ai-inference-manager|
wowplay|wowplay.service|?|wowplay|
'
OPT_thinq_sdx='iot iot_push_secure'
OPT_thinq_hosts='eic.lgtviot.com connect-client.lgthinq.com common.lgthinq.com kic-st-iotservice.lgthinq.com {ric}.lgtviot.com push.lgtviot.com'
OPT_thinq_hosts_t=''
OPT_thinq_settings='
network|bleAdvertisingOnOff|"off"
'
OPT_thinq_settings_t=''
OPT_thinq_apps=''
OPT_thinq_apps_t=''

# --- google-home
OPT_google_home_category='cloud'
OPT_google_home_name='Google Home hub'
OPT_google_home_what='Stops the Google Home hub.'
OPT_google_home_breaks='Google Home hub'
OPT_google_home_hook=''
OPT_google_home_warning=''
OPT_google_home_presets='recommended strict lockdown'; OPT_google_home_untested=0
OPT_google_home_spec='
google-home|google-home-controller.service|?|google-home-controller|||L=static
ghp-runtime||/media/system/apps/usr/palm/services/com.webos.ghp.runtime/com.webos.ghp.runtime|||com.webos.ghp.runtime|m,L=jailed,j=com.webos.ghp
'
OPT_google_home_spec_t=''
OPT_google_home_released=''
OPT_google_home_sdx=''
OPT_google_home_hosts=''
OPT_google_home_hosts_t=''
OPT_google_home_settings=''
OPT_google_home_settings_t=''
OPT_google_home_apps=''
OPT_google_home_apps_t=''

# --- buddy-sports
OPT_buddy_sports_category='cloud'
OPT_buddy_sports_name='LG Buddy and sports alerts'
OPT_buddy_sports_what='Stops LG Buddy and sports alerts.'
OPT_buddy_sports_breaks='LG Buddy, sports alerts'
OPT_buddy_sports_hook=''
OPT_buddy_sports_warning=''
OPT_buddy_sports_presets='recommended strict lockdown'; OPT_buddy_sports_untested=0
OPT_buddy_sports_spec='
buddyconnector|com.webos.service.buddyconnector.service|/usr/palm/services/com.webos.service.buddyconnector/com.webos.service.buddyconnector|||com.webos.service.buddyconnector|L=dynamic
sportsalarm||?|sportsalarm||com.webos.service.sportsalarm|L=dynamic
sportsalert||/usr/palm/services/com.webos.service.sportsalert/index.js|||com.webos.service.sportsalert|u,L=unified
'
OPT_buddy_sports_spec_t=''
OPT_buddy_sports_released=''
OPT_buddy_sports_sdx='iot_sports_secure buddy'
OPT_buddy_sports_hosts='{ric}.buddy.lgtviot.com'
OPT_buddy_sports_hosts_t=''
OPT_buddy_sports_settings='
general|sportsAlarm|"off"
'
OPT_buddy_sports_settings_t=''
OPT_buddy_sports_apps=''
OPT_buddy_sports_apps_t=''

# --- ai
OPT_ai_category='cloud'
OPT_ai_name='AI features'
OPT_ai_what='Stops LG'\''s cloud AI features.'
OPT_ai_breaks='Life-on-Screen art, AI agent'
OPT_ai_hook=''
OPT_ai_warning=''
OPT_ai_presets='strict lockdown'; OPT_ai_untested=0
OPT_ai_spec=''
OPT_ai_spec_t=''
OPT_ai_released=''
OPT_ai_sdx='sdp_ai_lab sdp_aiplatform_iot'
OPT_ai_hosts='eic.lab.lgtvcommon.com {ric}.lab.lgtvcommon.com'
OPT_ai_hosts_t=''
OPT_ai_settings=''
OPT_ai_settings_t=''
OPT_ai_apps='com.webos.app.aiagent com.webos.app.aipromotion'
OPT_ai_apps_t=''

# --- backup-presence
OPT_backup_presence_category='cloud'
OPT_backup_presence_name='Settings backup and presence'
OPT_backup_presence_what='Stops settings backup to LG and presence sensing.'
OPT_backup_presence_breaks='Settings backup'
OPT_backup_presence_hook=''
OPT_backup_presence_warning=''
OPT_backup_presence_presets='recommended strict lockdown'; OPT_backup_presence_untested=0
OPT_backup_presence_spec=''
OPT_backup_presence_spec_t=''
OPT_backup_presence_released=''
OPT_backup_presence_sdx=''
OPT_backup_presence_hosts=''
OPT_backup_presence_hosts_t=''
OPT_backup_presence_settings='
general|autoBackupEnabled|false
option|homeSensePresence|"off"
option|homeSenseAbsence|"off"
option|homeSenseAccount|"off"
'
OPT_backup_presence_settings_t=''
OPT_backup_presence_apps=''
OPT_backup_presence_apps_t=''

# --- universal-control
OPT_universal_control_category='cloud'
OPT_universal_control_name='Universal Control and LAN device scanning'
OPT_universal_control_what='Stops Universal Control and its network scanning.'
OPT_universal_control_breaks='Universal Control'
OPT_universal_control_hook=''
OPT_universal_control_warning=''
OPT_universal_control_presets='lockdown'; OPT_universal_control_untested=0
OPT_universal_control_spec='
iconnectivity||/usr/sbin/iconnectivity|iconnectivity||com.webos.service.ics|L=dynamic
'
OPT_universal_control_spec_t=''
OPT_universal_control_released=''
OPT_universal_control_sdx=''
OPT_universal_control_hosts=''
OPT_universal_control_hosts_t=''
OPT_universal_control_settings=''
OPT_universal_control_settings_t=''
OPT_universal_control_apps=''
OPT_universal_control_apps_t=''

# --- trackers
OPT_trackers_category='network'
OPT_trackers_name='Tracker hostnames'
OPT_trackers_what='Blocks ad, analytics and tracking hostnames.'
OPT_trackers_breaks=''
OPT_trackers_hook=''
OPT_trackers_warning=''
OPT_trackers_presets='recommended strict lockdown'; OPT_trackers_untested=0
OPT_trackers_spec=''
OPT_trackers_spec_t=''
OPT_trackers_released=''
OPT_trackers_sdx=''
OPT_trackers_hosts='demdex.net dpm.demdex.net everesttech.net criteo.com doubleclick.net sxp.smartclip.net hbbtv.smartclip.net es.container.enhanced.live bitv.eu ottera.tv stream.ads.ottera.tv otteravision.com lge-oo-es.otteravision.com adstk.io eu-ssp-pix.adstk.io eu-imp-pix.adstk.io smartadserver.com prg.smartadserver.com axiom.co api.axiom.co ipify.org api.ipify.org onetrust.io mobile-data.onetrust.io googletagmanager.com www.googletagmanager.com dns.google dns.google.com cloudflare-dns.com mozilla.cloudflare-dns.com chrome.cloudflare-dns.com one.one.one.one dns.quad9.net dns9.quad9.net doh.opendns.com dns.adguard.com dns.adguard-dns.com doh.cleanbrowsing.org dns.nextdns.io www.google-analytics.com region1.google-analytics.com analytics.google.com'
OPT_trackers_hosts_t=''
OPT_trackers_settings=''
OPT_trackers_settings_t=''
OPT_trackers_apps=''
OPT_trackers_apps_t=''

# --- store-traffic
OPT_store_traffic_category='network'
OPT_store_traffic_name='LG Store and account traffic'
OPT_store_traffic_what='Cuts the LG servers behind the Content Store.'
OPT_store_traffic_breaks='App installs and updates, Home content'
OPT_store_traffic_hook=''
OPT_store_traffic_warning=''
OPT_store_traffic_presets='lockdown'; OPT_store_traffic_untested=0
OPT_store_traffic_spec=''
OPT_store_traffic_spec_t=''
OPT_store_traffic_released=''
OPT_store_traffic_sdx='sdp_apps sdp_apps_resource cpauth_secure wise_account sdp_home'
OPT_store_traffic_hosts=''
OPT_store_traffic_hosts_t=''
OPT_store_traffic_settings=''
OPT_store_traffic_settings_t=''
OPT_store_traffic_apps=''
OPT_store_traffic_apps_t=''

# --- remote-config
OPT_remote_config_category='network'
OPT_remote_config_name='Remote configuration'
OPT_remote_config_what='Cuts LG'\''s remote configuration servers.'
OPT_remote_config_breaks='Online programme guide'
OPT_remote_config_hook=''
OPT_remote_config_warning=''
OPT_remote_config_presets='lockdown'; OPT_remote_config_untested=0
OPT_remote_config_spec=''
OPT_remote_config_spec_t=''
OPT_remote_config_released=''
OPT_remote_config_sdx='service_setting_secure ibis_secure'
OPT_remote_config_hosts=''
OPT_remote_config_hosts_t=''
OPT_remote_config_settings=''
OPT_remote_config_settings_t=''
OPT_remote_config_apps=''
OPT_remote_config_apps_t=''

# --- remote-support
OPT_remote_support_category='access'
OPT_remote_support_name='Remote support and root hygiene'
OPT_remote_support_what='Stops LG remote support and locks down root access.'
OPT_remote_support_breaks='LG remote support'
OPT_remote_support_hook='remote'
OPT_remote_support_warning=''
OPT_remote_support_presets='recommended strict lockdown'; OPT_remote_support_untested=0
OPT_remote_support_spec='
remotediag|remotediag.service|?|remotediag||com.webos.service.remotediag|L=dynamic
'
OPT_remote_support_spec_t=''
OPT_remote_support_released=''
OPT_remote_support_sdx=''
OPT_remote_support_hosts=''
OPT_remote_support_hosts_t=''
OPT_remote_support_settings=''
OPT_remote_support_settings_t=''
OPT_remote_support_apps='com.webos.app.remoteservice com.webos.app.svcdiagnostics com.webos.app.store-demo com.webos.app.sync-demo com.webos.exampleapp.enyoapp.epg com.webos.exampleapp.groupowner com.webos.exampleapp.nav com.webos.exampleapp.qmlapp.client.negative.one com.webos.exampleapp.qmlapp.client.negative.two com.webos.exampleapp.qmlapp.client.positive.one com.webos.exampleapp.qmlapp.client.positive.two com.webos.exampleapp.qmlapp.discover com.webos.exampleapp.qmlapp.epg com.webos.exampleapp.qmlapp.hbbtv com.webos.exampleapp.qmlapp.livetv com.webos.exampleapp.qmlapp.search com.webos.exampleapp.systemui'
OPT_remote_support_apps_t=''

# --- account
OPT_account_category='access'
OPT_account_name='Block LG account'
OPT_account_what='Removes any LG account and blocks sign-in.'
OPT_account_breaks='Content Store installs, LG account features'
OPT_account_hook='account'
OPT_account_warning='Any LG account is removed and signing in is blocked. Turn this off when you need to sign in.'
OPT_account_presets='strict lockdown'; OPT_account_untested=0
OPT_account_spec=''
OPT_account_spec_t=''
OPT_account_released=''
OPT_account_sdx=''
OPT_account_hosts='{cc}.membership.lgwebostv.com {cc}.emp.lgsmartplatform.com {cc}.lgeapi.com'
OPT_account_hosts_t=''
OPT_account_settings=''
OPT_account_settings_t=''
OPT_account_apps=''
OPT_account_apps_t=''

# --- terms
OPT_terms_category='access'
OPT_terms_name='Terms prompts'
OPT_terms_what='Stops the '\''User Agreements'\'' prompt.'
OPT_terms_breaks=''
OPT_terms_hook='nag'
OPT_terms_warning=''
OPT_terms_presets='recommended strict lockdown'; OPT_terms_untested=0
OPT_terms_spec=''
OPT_terms_spec_t=''
OPT_terms_released=''
OPT_terms_sdx=''
OPT_terms_hosts=''
OPT_terms_hosts_t=''
OPT_terms_settings=''
OPT_terms_settings_t=''
OPT_terms_apps=''
OPT_terms_apps_t=''

EULA_IDS='S_VNG S_PRV S_TAD S_TAG S_ADG S_ADC S_ADD S_VDC S_VDD S_NVC S_NVD S_MKT S_DPA S_ALL'
EULA_FLAGS='acrAllowed acrOnAllowed acrAdAllowed acrGdprAllowed shoppingOnAllowed veranceOnAllowed voiceAllowed voice2Allowed marketingOnAllowed customAdAllowed customadsAllowed thirdPartySharingAllowed remoteDiagAllowed additionalDataAllowed additional1Allowed additional2Allowed additional3Allowed additional4Allowed additional5Allowed cookiesAllowed'
NEVER_HOSTS='lgtvonline.lge.com connectivitycheck.gstatic.com ngfts.lge.com tv.wiselg.com tv.wiselg.cn nextlgsdp.com lgtvsdp.com app.lgwebostv.com snu.lge.com su.lge.com'
NEVER_HOST_SUFFIXES='-ngfts.lge.com .ngfts.lge.com'
NEVER_HOST_PREFIXED='tv.wiselg.com tv.wiselg.cn nextlgsdp.com lgtvsdp.com app.lgwebostv.com'
OYG_RICS='aic eic kic cic ruc'
OYG_COUNTRIES='ae al ar at au ba be bg bh br by ca ch cl cm cn co cz de dk dz ec ee es fi fr gb gh gr hk hn hr hu id ie il in iq ir is it jo jp ke kh kr kw kz lb lk lt lu lv ly ma mk mm mn mu mw mx my na ng nl no nz om pa pe ph pk pl pt qa ro rs ru sa se sg si sk th tn tr tw ua ug us uz ve vn ye za zm zw'
